include $(THEOS)/makefiles/common.mk
TOOL_NAME = vedette-nicectl
vedette-nicectl_FILES = main.mm ../VDTNiceShared.mm ../VDTNiceStore.c
vedette-nicectl_FRAMEWORKS = Foundation
vedette-nicectl_CFLAGS = -fobjc-arc -I$(THEOS_PROJECT_DIR)/..
vedette-nicectl_INSTALL_PATH = /usr/libexec
include $(THEOS_MAKE_PATH)/tool.mk
